
export const countries = [
	{ code: 'AR', flag: '🇦🇷', phone: '54', name: 'Argentina'},
	{ code: 'AT', flag: '🇦🇹', phone: '43', name: 'Austria'},
	{ code: 'AU', flag: '🇦🇺', phone: '61', name: 'Australia'},
	{ code: 'BE', flag: '🇧🇪', phone: '32', name: 'Belgium'},
	{ code: 'BR', flag: '🇧🇷', phone: '55', name: 'Brazil'},
	{ code: 'CA', flag: '🇨🇦', phone: '1', name: 'Canada'},
	{ code: 'CH', flag: '🇨🇭', phone: '41', name: 'Switzerland'},
	{ code: 'CL', flag: '🇨🇱', phone: '56', name: 'Chile'},
	{ code: 'CN', flag: '🇨🇳', phone: '86', name: 'China'},
	{ code: 'CO', flag: '🇨🇴', phone: '57', name: 'Colombia'},
	{ code: 'DE', flag: '🇩🇪', phone: '49', name: 'Germany'},
	{ code: 'DK', flag: '🇩🇰', phone: '45', name: 'Denmark'},
	{ code: 'EG', flag: '🇪🇬', phone: '20', name: 'Egypt'},
	{ code: 'ES', flag: '🇪🇸', phone: '34', name: 'Spain'},
	{ code: 'FR', flag: '🇫🇷', phone: '33', name: 'France'},
	{ code: 'GB', flag: '🇬🇧', phone: '44', name: 'United Kingdom'},
	{ code: 'GR', flag: '🇬🇷', phone: '30', name: 'Greece'},
	{ code: 'HU', flag: '🇭🇺', phone: '36', name: 'Hungary'},
	{ code: 'ID', flag: '🇮🇩', phone: '62', name: 'Indonesia'},
	{ code: 'IN', flag: '🇮🇳', phone: '91', name: 'India'},
	{ code: 'IR', flag: '🇮🇷', phone: '98', name: 'Iran'},
	{ code: 'IT', flag: '🇮🇹', phone: '39', name: 'Italy'},
	{ code: 'JP', flag: '🇯🇵', phone: '81', name: 'Japan'},
	{ code: 'KR', flag: '🇰🇷', phone: '82', name: 'South Korea'},
	{ code: 'KZ', flag: '🇰🇿', phone: '7', name: 'Kazakhstan'},
	{ code: 'LK', flag: '🇱🇰', phone: '94', name: 'Sri Lanka'},
	{ code: 'MM', flag: '🇲🇲', phone: '95', name: 'Myanmar'},
	{ code: 'MX', flag: '🇲🇽', phone: '52', name: 'Mexico'},
	{ code: 'MY', flag: '🇲🇾', phone: '60', name: 'Malaysia'},
	{ code: 'NL', flag: '🇳🇱', phone: '31', name: 'Netherlands'},
	{ code: 'NO', flag: '🇳🇴', phone: '47', name: 'Norway'},
	{ code: 'NZ', flag: '🇳🇿', phone: '64', name: 'New Zealand'},
	{ code: 'PE', flag: '🇵🇪', phone: '51', name: 'Peru'},
	{ code: 'PH', flag: '🇵🇭', phone: '63', name: 'Philippines'},
	{ code: 'PK', flag: '🇵🇰', phone: '92', name: 'Pakistan'},
	{ code: 'PL', flag: '🇵🇱', phone: '48', name: 'Poland'},
	{ code: 'RO', flag: '🇷🇴', phone: '40', name: 'Romania'},
	{ code: 'RU', flag: '🇷🇺', phone: '7', name: 'Russia'},
	{ code: 'SE', flag: '🇸🇪', phone: '46', name: 'Sweden'},
	{ code: 'SG', flag: '🇸🇬', phone: '65', name: 'Singapore'},
	{ code: 'TH', flag: '🇹🇭', phone: '66', name: 'Thailand'},
	{ code: 'TR', flag: '🇹🇷', phone: '90', name: 'Turkey'},
	{ code: 'US', flag: '🇺🇸', phone: '1', name: 'United States'},
	{ code: 'VE', flag: '🇻🇪', phone: '58', name: 'Venezuela'},
	{ code: 'VN', flag: '🇻🇳', phone: '84', name: 'Vietnam'},
	{ code: 'ZA', flag: '🇿🇦', phone: '27', name: 'South Africa'},

	{ code: 'AE', flag: '🇦🇪', phone: '971', name: 'United Arab Emirates'},
	{ code: 'CR', flag: '🇨🇷', phone: '506', name: 'Costa Rica'},
	{ code: 'CY', flag: '🇨🇾', phone: '357', name: 'Cyprus'},
	{ code: 'CZ', flag: '🇨🇿', phone: '420', name: 'Czech Republic'},
	{ code: 'EC', flag: '🇪🇨', phone: '593', name: 'Ecuador'},
	{ code: 'EE', flag: '🇪🇪', phone: '372', name: 'Estonia'},
	{ code: 'EH', flag: '🇪🇭', phone: '212', name: 'Western Sahara'},
	{ code: 'FI', flag: '🇫🇮', phone: '358', name: 'Finland'},
	{ code: 'FM', flag: '🇫🇲', phone: '691', name: 'Micronesia'},
	{ code: 'GT', flag: '🇬🇹', phone: '502', name: 'Guatemala'},
	{ code: 'HK', flag: '🇭🇰', phone: '852', name: 'Hong Kong'},
	{ code: 'HR', flag: '🇭🇷', phone: '385', name: 'Croatia'},
	{ code: 'IE', flag: '🇮🇪', phone: '353', name: 'Ireland'},
	{ code: 'IL', flag: '🇮🇱', phone: '972', name: 'Israel'},
	{ code: 'IQ', flag: '🇮🇶', phone: '964', name: 'Iraq'},
	{ code: 'IS', flag: '🇮🇸', phone: '354', name: 'Iceland'},
	{ code: 'JO', flag: '🇯🇴', phone: '962', name: 'Jordan'},
	{ code: 'KE', flag: '🇰🇪', phone: '254', name: 'Kenya'},
	{ code: 'KG', flag: '🇰🇬', phone: '996', name: 'Kyrgyzstan'},
	{ code: 'KI', flag: '🇰🇮', phone: '686', name: 'Kiribati'},
	{ code: 'KP', flag: '🇰🇵', phone: '850', name: 'North Korea'},
	{ code: 'KW', flag: '🇰🇼', phone: '965', name: 'Kuwait'},
	{ code: 'LA', flag: '🇱🇦', phone: '856', name: 'Laos'},
	{ code: 'LB', flag: '🇱🇧', phone: '961', name: 'Lebanon'},
	{ code: 'LI', flag: '🇱🇮', phone: '423', name: 'Liechtenstein'},
	{ code: 'LR', flag: '🇱🇷', phone: '231', name: 'Liberia'},
	{ code: 'LS', flag: '🇱🇸', phone: '266', name: 'Lesotho'},
	{ code: 'LT', flag: '🇱🇹', phone: '370', name: 'Lithuania'},
	{ code: 'LU', flag: '🇱🇺', phone: '352', name: 'Luxembourg'},
	{ code: 'LV', flag: '🇱🇻', phone: '371', name: 'Latvia'},
	{ code: 'LY', flag: '🇱🇾', phone: '218', name: 'Libya'},
	{ code: 'MA', flag: '🇲🇦', phone: '212', name: 'Morocco'},
	{ code: 'MC', flag: '🇲🇨', phone: '377', name: 'Monaco'},
	{ code: 'MD', flag: '🇲🇩', phone: '373', name: 'Moldova'},
	{ code: 'ME', flag: '🇲🇪', phone: '382', name: 'Montenegro'},
	{ code: 'MG', flag: '🇲🇬', phone: '261', name: 'Madagascar'},
	{ code: 'MH', flag: '🇲🇭', phone: '692', name: 'Marshall Islands'},
	{ code: 'ML', flag: '🇲🇱', phone: '223', name: 'Mali'},
	{ code: 'MN', flag: '🇲🇳', phone: '976', name: 'Mongolia'},
	{ code: 'MR', flag: '🇲🇷', phone: '222', name: 'Mauritania'},
	{ code: 'MT', flag: '🇲🇹', phone: '356', name: 'Malta'},
	{ code: 'MU', flag: '🇲🇺', phone: '230', name: 'Mauritius'},
	{ code: 'MV', flag: '🇲🇻', phone: '960', name: 'Maldives'},
	{ code: 'MW', flag: '🇲🇼', phone: '265', name: 'Malawi'},
	{ code: 'MZ', flag: '🇲🇿', phone: '258', name: 'Mozambique'},
	{ code: 'NA', flag: '🇳🇦', phone: '264', name: 'Namibia'},
	{ code: 'NE', flag: '🇳🇪', phone: '227', name: 'Niger'},
	{ code: 'NG', flag: '🇳🇬', phone: '234', name: 'Nigeria'},
	{ code: 'NI', flag: '🇳🇮', phone: '505', name: 'Nicaragua'},
	{ code: 'NP', flag: '🇳🇵', phone: '977', name: 'Nepal'},
	{ code: 'NR', flag: '🇳🇷', phone: '674', name: 'Nauru'},
	{ code: 'OM', flag: '🇴🇲', phone: '968', name: 'Oman'},
	{ code: 'PA', flag: '🇵🇦', phone: '507', name: 'Panama'},
	{ code: 'PG', flag: '🇵🇬', phone: '675', name: 'Papua New Guinea'},
	{ code: 'PT', flag: '🇵🇹', phone: '351', name: 'Portugal'},
	{ code: 'PW', flag: '🇵🇼', phone: '680', name: 'Palau'},
	{ code: 'PY', flag: '🇵🇾', phone: '595', name: 'Paraguay'},
	{ code: 'QA', flag: '🇶🇦', phone: '974', name: 'Qatar'},
	{ code: 'RS', flag: '🇷🇸', phone: '381', name: 'Serbia'},
	{ code: 'RW', flag: '🇷🇼', phone: '250', name: 'Rwanda'},
	{ code: 'SA', flag: '🇸🇦', phone: '966', name: 'Saudi Arabia'},
	{ code: 'SB', flag: '🇸🇧', phone: '677', name: 'Solomon Islands'},
	{ code: 'SC', flag: '🇸🇨', phone: '248', name: 'Seychelles'},
	{ code: 'SD', flag: '🇸🇩', phone: '249', name: 'Sudan'},
	{ code: 'SI', flag: '🇸🇮', phone: '386', name: 'Slovenia'},
	{ code: 'SK', flag: '🇸🇰', phone: '421', name: 'Slovakia'},
	{ code: 'SL', flag: '🇸🇱', phone: '232', name: 'Sierra Leone'},
	{ code: 'SM', flag: '🇸🇲', phone: '378', name: 'San Marino'},
	{ code: 'SN', flag: '🇸🇳', phone: '221', name: 'Senegal'},
	{ code: 'SO', flag: '🇸🇴', phone: '252', name: 'Somalia'},
	{ code: 'SR', flag: '🇸🇷', phone: '597', name: 'Suriname'},
	{ code: 'SS', flag: '🇸🇸', phone: '211', name: 'South Sudan'},
	{ code: 'ST', flag: '🇸🇹', phone: '239', name: 'São Tomé and Príncipe'},
	{ code: 'SY', flag: '🇸🇾', phone: '963', name: 'Syria'},
	{ code: 'TG', flag: '🇹🇬', phone: '228', name: 'Togo'},
	{ code: 'TJ', flag: '🇹🇯', phone: '992', name: 'Tajikistan'},
	{ code: 'TL', flag: '🇹🇱', phone: '670', name: 'Timor-Leste'},
	{ code: 'TM', flag: '🇹🇲', phone: '993', name: 'Turkmenistan'},
	{ code: 'TN', flag: '🇹🇳', phone: '216', name: 'Tunisia'},
	{ code: 'TO', flag: '🇹🇴', phone: '676', name: 'Tonga'},
	{ code: 'TV', flag: '🇹🇻', phone: '688', name: 'Tuvalu'},
	{ code: 'TW', flag: '🇹🇼', phone: '886', name: 'Taiwan'},
	{ code: 'TZ', flag: '🇹🇿', phone: '255', name: 'Tanzania'},
	{ code: 'UA', flag: '🇺🇦', phone: '380', name: 'Ukraine'},
	{ code: 'UG', flag: '🇺🇬', phone: '256', name: 'Uganda'},
	{ code: 'UY', flag: '🇺🇾', phone: '598', name: 'Uruguay'},
	{ code: 'UZ', flag: '🇺🇿', phone: '998', name: 'Uzbekistan'},
	{ code: 'VA', flag: '🇻🇦', phone: '379', name: 'Vatican City'},
	{ code: 'VU', flag: '🇻🇺', phone: '678', name: 'Vanuatu'},
	{ code: 'WF', flag: '🇼🇫', phone: '681', name: 'Wallis & Futuna'},
	{ code: 'WS', flag: '🇼🇸', phone: '685', name: 'Samoa'},
	{ code: 'YE', flag: '🇾🇪', phone: '967', name: 'Yemen'},
	{ code: 'ZM', flag: '🇿🇲', phone: '260', name: 'Zambia'},
	{ code: 'ZW', flag: '🇿🇼', phone: '263', name: 'Zimbabwe' },

	{ code: 'KN', flag: '🇰🇳', phone: '1869', name: 'Saint Kitts and Nevis'},
	{ code: 'LC', flag: '🇱🇨', phone: '1758', name: 'Saint Lucia'},
	{ code: 'TC', flag: '🇹🇨', phone: '1649', name: 'Turks & Caicos Islands'},
	{ code: 'TT', flag: '🇹🇹', phone: '1868', name: 'Trinidad and Tobago'},
	{ code: 'VC', flag: '🇻🇨', phone: '1784', name: 'Saint Vincent and the Grenadines'},
]